---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
words:
  - appropes
  - automagically
  - autouse
  - bufnr
  - bufs
  - Cfgs
  - cmac
  - codelldb
  - dockerls
  - fastly
  - finalizers
  - fnameescape
  - fnamemodify
  - ghpr
  - gopls
  - hearstapps
  - hikaru
  - htmx
  - igoringress
  - imdb
  - ingressversion
  - ingressversions
  - jsonls
  - keymap
  - kopf
  - kubeprod
  - noremap
  - nvim
  - rockspec
  - rustaceanvim
  - taplo
  - venv
  - yamlls
